name: Deploy Terraform IAM

on:
  push:
    branches:
      - dev
      - qa
      - prod

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::699003538476:role/GitHubOIDCRole
          aws-region: ap-south-1

      - name: Show caller identity
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply (only in prod)
        if: github.ref == 'refs/heads/prod'
        run: terraform apply -auto-approve